version: "3.2"
services:
  lbrynet:
    image: 'lbry/lbrynet-tv:latest'
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: 1
    ports:
      - "5279:5279"
  player:
    image: 'lbry/lbrytv-player:fuda-next'
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: 1
    ports:
      - "8080:8080"
      - "5567:5567"
      - "5568:5568/udp"
      - "5568:5568/tcp"
    volumes:
      - "/tmp/reflector_cache:/tmp/player_cache"
      - "/tmp/reflector_cache:/tmp/transcoded_cache"
    entrypoint: >
      ./lbrytv_player
      --lbrynet=http://lbrynet:5279
      --bind=0.0.0.0:8080
      --disk-cache-dir="/tmp/player_cache"
      --disk-cache-size="1TB"
      --hot-cache-size="10GB"
      --prefetch=true
      --upstream-reflector="reflector.lbry.com:5568"
      --transcoder-video-path=/tmp/transcoded_cache
      --transcoder-video-size=200GB
      --transcoder-addr=http://t0.lbry.tv:18081
    environment:
      - PLAYER_NAME=my-own-player
    depends_on:
      - lbrynet
      - docker-host
  watchtower:
    image: 'containrrr/watchtower'
    restart: always
    command: "--interval 30 --cleanup --label-enable"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
