version: '3.2'

services:
  lbrynet:
    image: lbry/lbrynet-tv:latest
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: true

  player:
    image: lbry/lbrytv-player:latest
    restart: always
    volumes:
    - /tmp/player_cache:/tmp/player_cache
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
    - "8080:8080"
    entrypoint: /app/lbrytv_player --cache_size=100GB --lbrynet=http://lbrynet:5279 --reflector=refractor.lbry.com:5568 --bind=0.0.0.0:8080 --profile
    depends_on:
    - lbrynet

  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --interval 30 --cleanup --label-enable
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
