version: "3.2"
services:
  lbrynet:
    image: 'lbry/lbrynet-tv:latest'
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: true
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    environment:
      - PORTS=5567
  player:
    image: 'lbry/lbrytv-player:latest'
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-group: lbrytv
        awslogs-region: us-east-1
        awslogs-stream: "player-player7.lbry.tv"
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
      - "8080:8080"
    volumes:
      - "/tmp/player_cache:/tmp/player_cache"
    entrypoint: >
      ./lbrytv_player
      --cache_size=100GB
      --lbrynet=http://lbrynet:5279
#      --reflector=docker-host:5567
      --reflector=reflector.lbry.com:5568
      --bind=0.0.0.0:8080
      --profile=True
      --reflector_protocol=http3
    environment:
      - PLAYER_NAME=my-own-player
    depends_on:
      - lbrynet
      - docker-host
  watchtower:
    image: 'containrrr/watchtower'
    restart: always
    command: "--interval 30 --cleanup --label-enable"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
