version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.16
      - image: lbry/lbrynet-tv:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-v2-{{ checksum "go.sum" }}
      - run: make test_circleci
      - run: git reset --hard HEAD
      - save_cache:
          key: go-mod-cache-v2-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  release:
    docker:
      - image: circleci/golang:1.16
      - image: lbry/lbrynet-tv:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-v2-{{ checksum "go.sum" }}
      - run: make test_circleci
      - run: git reset --hard HEAD
      - setup_remote_docker
      - run:
          name: Build release image
          command: |
            curl -sOL https://git.io/goreleaser && chmod +x ./goreleaser && mv ./goreleaser /tmp/goreleaser
            /tmp/goreleaser --rm-dist --skip-publish
      - run:
          name: Publish Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            make publish_image


workflows:
  version: 2
  integrate:
    jobs:
      - test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
